// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(GBOHContext))]
    [Migration("20191212174456_UpdatingDatabase")]
    partial class UpdatingDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuisineId");

                    b.ToTable("Cuisine");

                    b.HasData(
                        new
                        {
                            CuisineId = 1,
                            Name = "Asian"
                        },
                        new
                        {
                            CuisineId = 2,
                            Name = "Italian"
                        },
                        new
                        {
                            CuisineId = 3,
                            Name = "Indian"
                        },
                        new
                        {
                            CuisineId = 4,
                            Name = "European"
                        },
                        new
                        {
                            CuisineId = 5,
                            Name = "French"
                        });
                });

            modelBuilder.Entity("api.Models.Diet", b =>
                {
                    b.Property<int>("DietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DietId");

                    b.ToTable("Diet");

                    b.HasData(
                        new
                        {
                            DietId = 1,
                            Name = "Vegan"
                        },
                        new
                        {
                            DietId = 2,
                            Name = "Vegetarian"
                        },
                        new
                        {
                            DietId = 3,
                            Name = "Gluten-free"
                        },
                        new
                        {
                            DietId = 4,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("api.Models.DishType", b =>
                {
                    b.Property<int>("DishTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishTypeId");

                    b.ToTable("DishType");

                    b.HasData(
                        new
                        {
                            DishTypeId = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            DishTypeId = 2,
                            Name = "Dinner"
                        },
                        new
                        {
                            DishTypeId = 3,
                            Name = "Lunch"
                        },
                        new
                        {
                            DishTypeId = 4,
                            Name = "Dessert"
                        },
                        new
                        {
                            DishTypeId = 5,
                            Name = "Salad"
                        });
                });

            modelBuilder.Entity("api.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            ImageURL = "url",
                            Name = "Tomato",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 2,
                            ImageURL = "url",
                            Name = "Cucumber",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 3,
                            ImageURL = "url",
                            Name = "Potato",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 4,
                            ImageURL = "url",
                            Name = "Onion",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 5,
                            ImageURL = "url",
                            Name = "Asparagus",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 6,
                            ImageURL = "url",
                            Name = "Chilli peppers",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 7,
                            ImageURL = "url",
                            Name = "Lettuce",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 8,
                            ImageURL = "url",
                            Name = "Leeks",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 9,
                            ImageURL = "url",
                            Name = "Eggplant",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 10,
                            ImageURL = "url",
                            Name = "Mushroom",
                            Type = "Fungi"
                        },
                        new
                        {
                            IngredientId = 11,
                            ImageURL = "url",
                            Name = "Peas",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 12,
                            ImageURL = "url",
                            Name = "Pumpkin",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 13,
                            ImageURL = "url",
                            Name = "Pork",
                            Type = "Meat"
                        },
                        new
                        {
                            IngredientId = 14,
                            ImageURL = "url",
                            Name = "Chicken",
                            Type = "Meat"
                        },
                        new
                        {
                            IngredientId = 15,
                            ImageURL = "url",
                            Name = "Beans",
                            Type = "Grain"
                        },
                        new
                        {
                            IngredientId = 16,
                            ImageURL = "url",
                            Name = "Egg",
                            Type = "Egg"
                        },
                        new
                        {
                            IngredientId = 17,
                            ImageURL = "url",
                            Name = "Spahetti",
                            Type = "Pasta"
                        },
                        new
                        {
                            IngredientId = 18,
                            ImageURL = "url",
                            Name = "Macaroni",
                            Type = "Pasta"
                        },
                        new
                        {
                            IngredientId = 19,
                            ImageURL = "url",
                            Name = "Rigatoni",
                            Type = "Pasta"
                        },
                        new
                        {
                            IngredientId = 20,
                            ImageURL = "url",
                            Name = "Asian chile pepper sauce",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 21,
                            ImageURL = "url",
                            Name = "Maple syrup",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 22,
                            ImageURL = "url",
                            Name = "Soy sauce",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 23,
                            ImageURL = "url",
                            Name = "Mayonnaise",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 24,
                            ImageURL = "url",
                            Name = "Rice Vinegar",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 25,
                            ImageURL = "url",
                            Name = "Salt",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 26,
                            ImageURL = "url",
                            Name = "Black Pepper",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 27,
                            ImageURL = "url",
                            Name = "Lime",
                            Type = "Fruit"
                        },
                        new
                        {
                            IngredientId = 28,
                            ImageURL = "url",
                            Name = "Garlic",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 29,
                            ImageURL = "url",
                            Name = "Vegetable oil",
                            Type = "Condiment"
                        },
                        new
                        {
                            IngredientId = 30,
                            ImageURL = "url",
                            Name = "White sugar",
                            Type = "Sweetener"
                        },
                        new
                        {
                            IngredientId = 31,
                            ImageURL = "url",
                            Name = "Molasses",
                            Type = "Sweetener"
                        },
                        new
                        {
                            IngredientId = 32,
                            ImageURL = "url",
                            Name = "Flour",
                            Type = "Grain"
                        },
                        new
                        {
                            IngredientId = 33,
                            ImageURL = "url",
                            Name = "Baking Powder",
                            Type = "Food additive"
                        },
                        new
                        {
                            IngredientId = 34,
                            ImageURL = "url",
                            Name = "Ground Cinnamon",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 35,
                            ImageURL = "url",
                            Name = "Ground Cloves",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 36,
                            ImageURL = "url",
                            Name = "Ground Nutmeg",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 37,
                            ImageURL = "url",
                            Name = "Ground Ginger",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 38,
                            ImageURL = "url",
                            Name = "Baking Soda",
                            Type = "Food additive"
                        },
                        new
                        {
                            IngredientId = 39,
                            ImageURL = "url",
                            Name = "Butter",
                            Type = "Dairy"
                        },
                        new
                        {
                            IngredientId = 40,
                            ImageURL = "url",
                            Name = "Milk",
                            Type = "Dairy"
                        },
                        new
                        {
                            IngredientId = 41,
                            ImageURL = "url",
                            Name = "Cranberry",
                            Type = "Fruit"
                        },
                        new
                        {
                            IngredientId = 42,
                            ImageURL = "url",
                            Name = "Vanilla",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 43,
                            ImageURL = "url",
                            Name = "Whipping Cream",
                            Type = "Topping"
                        },
                        new
                        {
                            IngredientId = 44,
                            ImageURL = "url",
                            Name = "Cabbage",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 45,
                            ImageURL = "url",
                            Name = "Jalapeno",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 46,
                            ImageURL = "url",
                            Name = "Red onion",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 47,
                            ImageURL = "url",
                            Name = "Carrot",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 48,
                            ImageURL = "url",
                            Name = "Coriander",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 49,
                            ImageURL = "url",
                            Name = "Bacon",
                            Type = "Meat"
                        },
                        new
                        {
                            IngredientId = 50,
                            ImageURL = "url",
                            Name = "Cheese",
                            Type = "Diary"
                        },
                        new
                        {
                            IngredientId = 51,
                            ImageURL = "url",
                            Name = "Pork sausage",
                            Type = "Meat"
                        },
                        new
                        {
                            IngredientId = 52,
                            ImageURL = "url",
                            Name = "Refrigerated Roll Dough",
                            Type = "Grain"
                        },
                        new
                        {
                            IngredientId = 53,
                            ImageURL = "url",
                            Name = "Mozarrella",
                            Type = "Diary"
                        },
                        new
                        {
                            IngredientId = 54,
                            ImageURL = "url",
                            Name = "Cheddar",
                            Type = "Diary"
                        },
                        new
                        {
                            IngredientId = 55,
                            ImageURL = "url",
                            Name = "Oregano",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 56,
                            ImageURL = "url",
                            Name = "Bread",
                            Type = "Grain"
                        },
                        new
                        {
                            IngredientId = 57,
                            ImageURL = "url",
                            Name = "Celery",
                            Type = "Vegetable"
                        },
                        new
                        {
                            IngredientId = 58,
                            ImageURL = "url",
                            Name = "Paprika",
                            Type = "Grain"
                        },
                        new
                        {
                            IngredientId = 59,
                            ImageURL = "url",
                            Name = "Hot pepper sauce",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 60,
                            ImageURL = "url",
                            Name = "Beef",
                            Type = "Spice"
                        },
                        new
                        {
                            IngredientId = 61,
                            ImageURL = "url",
                            Name = "Thousand Island",
                            Type = "Topping"
                        },
                        new
                        {
                            IngredientId = 62,
                            ImageURL = "url",
                            Name = "Sauerkraut",
                            Type = "Side dish"
                        },
                        new
                        {
                            IngredientId = 63,
                            ImageURL = "url",
                            Name = "Condensed Cream of Chicken soup",
                            Type = "Side dish"
                        },
                        new
                        {
                            IngredientId = 64,
                            ImageURL = "url",
                            Name = "Refrigerated Biscuit Dough",
                            Type = "Grain"
                        });
                });

            modelBuilder.Entity("api.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReviewsNumber")
                        .HasColumnType("int");

                    b.Property<double>("Stars")
                        .HasColumnType("float");

                    b.HasKey("RatingId");

                    b.ToTable("Rating");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            ReviewsNumber = 232,
                            Stars = 5.0
                        },
                        new
                        {
                            RatingId = 2,
                            ReviewsNumber = 156,
                            Stars = 4.2999999999999998
                        },
                        new
                        {
                            RatingId = 3,
                            ReviewsNumber = 33,
                            Stars = 4.2000000000000002
                        },
                        new
                        {
                            RatingId = 4,
                            ReviewsNumber = 20,
                            Stars = 3.7999999999999998
                        },
                        new
                        {
                            RatingId = 5,
                            ReviewsNumber = 56,
                            Stars = 4.0999999999999996
                        },
                        new
                        {
                            RatingId = 6,
                            ReviewsNumber = 32,
                            Stars = 2.7999999999999998
                        },
                        new
                        {
                            RatingId = 7,
                            ReviewsNumber = 122,
                            Stars = 3.7000000000000002
                        },
                        new
                        {
                            RatingId = 8,
                            ReviewsNumber = 174,
                            Stars = 4.9000000000000004
                        },
                        new
                        {
                            RatingId = 9,
                            ReviewsNumber = 10,
                            Stars = 5.0
                        },
                        new
                        {
                            RatingId = 10,
                            ReviewsNumber = 87,
                            Stars = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("api.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CuisineId")
                        .HasColumnType("int");

                    b.Property<int>("DishTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CuisineId");

                    b.HasIndex("DishTypeId");

                    b.HasIndex("RatingId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CuisineId = 1,
                            DishTypeId = 2,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 90m,
                            RatingId = 1,
                            Time = 35,
                            Title = "Rusty Chicken Thighs"
                        },
                        new
                        {
                            RecipeId = 2,
                            CuisineId = 2,
                            DishTypeId = 4,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 80m,
                            RatingId = 2,
                            Time = 65,
                            Title = "Gingerbread Biscotti"
                        },
                        new
                        {
                            RecipeId = 3,
                            CuisineId = 3,
                            DishTypeId = 4,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 120m,
                            RatingId = 3,
                            Time = 120,
                            Title = "Fresh Cranberry Cake"
                        },
                        new
                        {
                            RecipeId = 4,
                            CuisineId = 4,
                            DishTypeId = 5,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 50m,
                            RatingId = 4,
                            Time = 20,
                            Title = "Taco Slaw"
                        },
                        new
                        {
                            RecipeId = 5,
                            CuisineId = 3,
                            DishTypeId = 1,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 75m,
                            RatingId = 5,
                            Time = 50,
                            Title = "Quick Quiche"
                        },
                        new
                        {
                            RecipeId = 6,
                            CuisineId = 2,
                            DishTypeId = 1,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 70m,
                            RatingId = 6,
                            Time = 50,
                            Title = "Egg and Sausage Casserole"
                        },
                        new
                        {
                            RecipeId = 7,
                            CuisineId = 3,
                            DishTypeId = 3,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 40m,
                            RatingId = 7,
                            Time = 5,
                            Title = "Spicy Grilled Cheese Sandwich"
                        },
                        new
                        {
                            RecipeId = 8,
                            CuisineId = 5,
                            DishTypeId = 3,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 110m,
                            RatingId = 8,
                            Time = 45,
                            Title = "Di's Delicious Deluxe Deviled Eggs"
                        },
                        new
                        {
                            RecipeId = 9,
                            CuisineId = 1,
                            DishTypeId = 3,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 60m,
                            RatingId = 9,
                            Time = 25,
                            Title = "Reuben Sandwich II"
                        },
                        new
                        {
                            RecipeId = 10,
                            CuisineId = 2,
                            DishTypeId = 4,
                            ImageURL = "./imagesandicons/food-plate.png",
                            Price = 95m,
                            RatingId = 10,
                            Time = 300,
                            Title = "Slow Cooker Chicken and Dumplings"
                        });
                });

            modelBuilder.Entity("api.Models.RecipeDiet", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "DietId");

                    b.HasIndex("DietId");

                    b.ToTable("RecipeDiets");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 2,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 3,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 4,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 5,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 6,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 7,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 8,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 9,
                            DietId = 4
                        },
                        new
                        {
                            RecipeId = 10,
                            DietId = 4
                        });
                });

            modelBuilder.Entity("api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 20,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 21,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 22,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 23,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 24,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 25,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 26,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 27,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 28,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientId = 16,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 29,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 30,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 31,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 32,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 33,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 34,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 35,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 36,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 37,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientId = 32,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 38,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 25,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 30,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 39,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 16,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 40,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 41,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 42,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 43,
                            RecipeId = 3
                        },
                        new
                        {
                            IngredientId = 27,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 44,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 45,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 46,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 47,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 48,
                            RecipeId = 4
                        },
                        new
                        {
                            IngredientId = 49,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 50,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 16,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 39,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 25,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 32,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 40,
                            RecipeId = 5
                        },
                        new
                        {
                            IngredientId = 16,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 51,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 52,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 53,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 54,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 55,
                            RecipeId = 6
                        },
                        new
                        {
                            IngredientId = 39,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 56,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 1,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 50,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 45,
                            RecipeId = 7
                        },
                        new
                        {
                            IngredientId = 16,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 57,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 23,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 25,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 59,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 58,
                            RecipeId = 8
                        },
                        new
                        {
                            IngredientId = 39,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 56,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 50,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 60,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 61,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 62,
                            RecipeId = 9
                        },
                        new
                        {
                            IngredientId = 39,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredientId = 14,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredientId = 4,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredientId = 63,
                            RecipeId = 10
                        },
                        new
                        {
                            IngredientId = 64,
                            RecipeId = 10
                        });
                });

            modelBuilder.Entity("api.Models.RecipeRecipeStep", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeStepId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeRecipeSteps");

                    b.HasData(
                        new
                        {
                            RecipeStepId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeStepId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeStepId = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeStepId = 4,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeStepId = 5,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeStepId = 6,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeStepId = 7,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeStepId = 8,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeStepId = 9,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeStepId = 10,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeStepId = 11,
                            RecipeId = 3
                        },
                        new
                        {
                            RecipeStepId = 12,
                            RecipeId = 3
                        },
                        new
                        {
                            RecipeStepId = 13,
                            RecipeId = 3
                        },
                        new
                        {
                            RecipeStepId = 14,
                            RecipeId = 3
                        },
                        new
                        {
                            RecipeStepId = 15,
                            RecipeId = 4
                        },
                        new
                        {
                            RecipeStepId = 16,
                            RecipeId = 6
                        },
                        new
                        {
                            RecipeStepId = 17,
                            RecipeId = 6
                        },
                        new
                        {
                            RecipeStepId = 18,
                            RecipeId = 6
                        },
                        new
                        {
                            RecipeStepId = 19,
                            RecipeId = 6
                        },
                        new
                        {
                            RecipeStepId = 20,
                            RecipeId = 7
                        },
                        new
                        {
                            RecipeStepId = 21,
                            RecipeId = 8
                        },
                        new
                        {
                            RecipeStepId = 22,
                            RecipeId = 8
                        },
                        new
                        {
                            RecipeStepId = 23,
                            RecipeId = 8
                        },
                        new
                        {
                            RecipeStepId = 24,
                            RecipeId = 9
                        },
                        new
                        {
                            RecipeStepId = 25,
                            RecipeId = 9
                        },
                        new
                        {
                            RecipeStepId = 26,
                            RecipeId = 9
                        },
                        new
                        {
                            RecipeStepId = 27,
                            RecipeId = 10
                        },
                        new
                        {
                            RecipeStepId = 28,
                            RecipeId = 10
                        });
                });

            modelBuilder.Entity("api.Models.RecipeStep", b =>
                {
                    b.Property<int>("RecipeStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecipeStepDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeStepId");

                    b.ToTable("RecipeStep");

                    b.HasData(
                        new
                        {
                            RecipeStepId = 1,
                            RecipeStepDescription = "Mash garlic to a paste with a mortar and pestle. Mix chile pepper sauce, maple syrup, soy sauce, mayonnaise, and rice vinegar into garlic until marinade is thoroughly combined."
                        },
                        new
                        {
                            RecipeStepId = 2,
                            RecipeStepDescription = "Transfer chicken thighs to a large flat container (such as a baking dish) and pour marinade over chicken; stir until chicken is coated. Cover dish with plastic wrap and refrigerate about 3 hours; if preferred, let stand about 30 minutes at room temperature. Unwrap dish and sprinkle with salt."
                        },
                        new
                        {
                            RecipeStepId = 3,
                            RecipeStepDescription = "Preheat charcoal grill to high heat."
                        },
                        new
                        {
                            RecipeStepId = 4,
                            RecipeStepDescription = "Place chicken thighs onto the hot grill with smooth sides down. Cook until chicken shows grill marks, about 3 minutes. Turn chicken over and cook until other side shows grill marks, about 5 minutes. Continue to cook, moving them occasionally and turning over every 2 minutes, until meat is no longer pink inside and the thighs are golden brown, 10 to 12 minutes."
                        },
                        new
                        {
                            RecipeStepId = 5,
                            RecipeStepDescription = "Transfer chicken to a platter, let rest for 5 minutes, and serve garnished with lime wedges."
                        },
                        new
                        {
                            RecipeStepId = 6,
                            RecipeStepDescription = "Preheat the oven to 375 degrees F (190 degrees C). Grease a cookie sheet."
                        },
                        new
                        {
                            RecipeStepId = 7,
                            RecipeStepDescription = "In a large bowl, mix together oil, sugar, eggs, and molasses. In another bowl, combine flours, baking powder, ginger, cinnamon, cloves, and nutmeg; mix into egg mixture to form a stiff dough."
                        },
                        new
                        {
                            RecipeStepId = 8,
                            RecipeStepDescription = "Divide dough in half, and shape each half into a roll the length of the cookie. Place rolls on cookie sheet, and pat down to flatten the dough to 1/2 inch thickness"
                        },
                        new
                        {
                            RecipeStepId = 9,
                            RecipeStepDescription = "Bake in preheated oven for 25 minutes. Remove from oven, and set aside to cool."
                        },
                        new
                        {
                            RecipeStepId = 10,
                            RecipeStepDescription = "When cool enough to touch, cut into 1/2 inch thick diagonal slices. Place sliced biscotti on cookie sheet, and bake an additional 5 to 7 minutes on each side, or until toasted and crispy."
                        },
                        new
                        {
                            RecipeStepId = 11,
                            RecipeStepDescription = "Preheat oven to 350 degrees F (175 degrees C). Grease a 9x13-inch baking dish."
                        },
                        new
                        {
                            RecipeStepId = 12,
                            RecipeStepDescription = "Combine flour, baking soda, and salt in a bowl. Beat 1 cup sugar and 3 tablespoons melted butter with a whisk until well mixed. Add eggs and beat until smooth. Stir flour mixture and milk into egg mixture until batter is well blended. Fold cranberries into batter until just mixed and pour into prepared baking dish."
                        },
                        new
                        {
                            RecipeStepId = 13,
                            RecipeStepDescription = "Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 30 minutes."
                        },
                        new
                        {
                            RecipeStepId = 14,
                            RecipeStepDescription = "For sauce, heat 1 cup sugar, 1/2 cup butter, heavy cream, and vanilla extract in a saucepan over medium-low heat; cook and stir cream sauce until sugar is dissolved, about 10 minutes. Pour hot sauce over hot cake. Allow cake to cool in the baking dish for 10 minutes before removing to cool completely on a wire rack."
                        },
                        new
                        {
                            RecipeStepId = 15,
                            RecipeStepDescription = "In a bowl, mix together the cabbage, jalapeno pepper, red onion, carrot, cilantro, and lime juice."
                        },
                        new
                        {
                            RecipeStepId = 16,
                            RecipeStepDescription = "Place bacon in a large, deep skillet. Cook over medium high heat until evenly brown. Drain, crumble and set aside."
                        },
                        new
                        {
                            RecipeStepId = 17,
                            RecipeStepDescription = "Preheat oven to 350 degrees F (175 degrees C). Lightly grease a 9 inch pie pan."
                        },
                        new
                        {
                            RecipeStepId = 18,
                            RecipeStepDescription = "Line bottom of pie plate with cheese and crumbled bacon. Combine eggs, butter, onion, salt, flour and milk; whisk together until smooth; pour into pie pan."
                        },
                        new
                        {
                            RecipeStepId = 19,
                            RecipeStepDescription = "Bake in preheated oven for 35 minutes, until set. Serve hot or cold."
                        },
                        new
                        {
                            RecipeStepId = 20,
                            RecipeStepDescription = "Heat a large skillet over low heat. Spread butter or margarine onto one side of two slices of bread. Place both pieces buttered side down in the skillet. Lay a slice of cheese on each one, and top with slices of tomato, onion and jalapeno. Butter one side of the remaining slices of bread, and place on top buttered side up. When the bottom of the sandwiches are toasted, flip and fry until brown on the other side."
                        },
                        new
                        {
                            RecipeStepId = 21,
                            RecipeStepDescription = "Place eggs in a medium saucepan and cover with cold water. Bring water to a boil and immediately remove from heat. Cover and let eggs stand in hot water for 10 to 12 minutes. Remove from hot water, cool and peel."
                        },
                        new
                        {
                            RecipeStepId = 22,
                            RecipeStepDescription = "Cut eggs in half. Remove yolks and place in a medium bowl. Mash together with celery, onion, mayonnaise, salt and hot pepper sauce."
                        },
                        new
                        {
                            RecipeStepId = 23,
                            RecipeStepDescription = "Stuff the egg white halves with the egg yolk mixture. Sprinkle eggs with paprika. Chill covered in the refrigerator until serving."
                        },
                        new
                        {
                            RecipeStepId = 24,
                            RecipeStepDescription = "Preheat a large skillet or griddle on medium heat."
                        },
                        new
                        {
                            RecipeStepId = 25,
                            RecipeStepDescription = "Lightly butter one side of bread slices. Spread non-buttered sides with Thousand Island dressing. On 4 bread slices, layer 1 slice Swiss cheese, 2 slices corned beef, 1/4 cup sauerkraut and second slice of Swiss cheese. Top with remaining bread slices, buttered sides out."
                        },
                        new
                        {
                            RecipeStepId = 26,
                            RecipeStepDescription = "Grill sandwiches until both sides are golden brown, about 5 minutes per side. Serve hot."
                        },
                        new
                        {
                            RecipeStepId = 27,
                            RecipeStepDescription = "Place the chicken, butter, soup, and onion in a slow cooker, and fill with enough water to cover."
                        },
                        new
                        {
                            RecipeStepId = 28,
                            RecipeStepDescription = "Cover, and cook for 5 to 6 hours on High. About 30 minutes before serving, place the torn biscuit dough in the slow cooker. Cook until the dough is no longer raw in the center."
                        });
                });

            modelBuilder.Entity("api.Models.Recipe", b =>
                {
                    b.HasOne("api.Models.Cuisine", "Cuisine")
                        .WithMany("Recipes")
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.DishType", "DishType")
                        .WithMany("Recipes")
                        .HasForeignKey("DishTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Rating", "Rating")
                        .WithMany("Recipes")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.RecipeDiet", b =>
                {
                    b.HasOne("api.Models.Diet", "Diet")
                        .WithMany("RecipeDiets")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Recipe", "Recipe")
                        .WithMany("RecipeDiets")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.RecipeRecipeStep", b =>
                {
                    b.HasOne("api.Models.Recipe", "Recipe")
                        .WithMany("RecipeRecipeSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.RecipeStep", "RecipeStep")
                        .WithMany("RecipeRecipeSteps")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
